content: |-
  # Example: Quickstart

  **Notes:**

  - Wayfinder will start up with an initial local administrator user (not configured to use an IDP).
  - Terraform is not configured to use Cloud Storage as a backend, and so state will be written locally.
  - Any sensitive values (e.g. licence key) are passed directly as a variable to the module.

  ## Deployment

  1. Create a Cloud DNS Managed Zone in GCP and ensure the domain is delegated to the GCP nameservers.
  2. Copy the `terraform.tfvars.example` file to `terraform.tfvars` and update with your values.
  3. Run `terraform init -upgrade`
  4. Run `terraform apply`

  ## Updating Docs

  The `terraform-docs` utility is used to generate this README. Follow the below steps to update:

  1. Make changes to the `.terraform-docs.yml` file
  2. Fetch the `terraform-docs` binary (https://terraform-docs.io/user-guide/installation/)
  3. Run `terraform-docs markdown table --output-file ${PWD}/README.md --output-mode inject .`

  {{ .Inputs }}

  {{ .Outputs }}
